// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_project/test/infrastructure/repositories/product_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_project/src/infrastructure/data_sources/network/i_products_data_source.dart'
    as _i3;
import 'package:flutter_project/src/infrastructure/dtos/prodcut_image/product_image_dto.dart'
    as _i2;
import 'package:flutter_project/src/infrastructure/dtos/product/product_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeProductImageDto_0 extends _i1.Fake implements _i2.ProductImageDto {}

/// A class which mocks [IProductDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductDataSource extends _i1.Mock
    implements _i3.IProductDataSource {
  MockIProductDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.ProductDto>> watchAll() =>
      (super.noSuchMethod(Invocation.method(#watchAll, []),
              returnValue: Stream<List<_i5.ProductDto>>.empty())
          as _i4.Stream<List<_i5.ProductDto>>);
  @override
  _i4.Future<dynamic> update(_i5.ProductDto? product) =>
      (super.noSuchMethod(Invocation.method(#update, [product]),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<dynamic> delete(String? id) =>
      (super.noSuchMethod(Invocation.method(#delete, [id]),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<_i2.ProductImageDto> getDownloadUrl(String? filename) =>
      (super.noSuchMethod(Invocation.method(#getDownloadUrl, [filename]),
              returnValue:
                  Future<_i2.ProductImageDto>.value(_FakeProductImageDto_0()))
          as _i4.Future<_i2.ProductImageDto>);
}
