name: flutter_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  auto_size_text: ^3.0.0

  cloud_firestore: ^3.1.16

  currency_text_input_formatter: ^2.1.5

  dartz: ^0.10.1

  flutter_bloc: ^8.0.1

  firebase_core: ^1.17.0

  flutter_rating_bar: ^4.0.1

  firebase_storage: ^10.2.17

  freezed_annotation: ^2.0.3

  get_it: ^7.2.0

  intl: ^0.17.0

  json_annotation: ^4.5.0

  rxdart: ^0.27.3

  shimmer_animation: ^2.1.0+1

  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.3

  build_runner:

  faker: ^2.0.0

  fake_cloud_firestore: ^1.2.2
  
  firebase_storage_mocks: ^0.5.0

  freezed: ^2.0.3+1

  flutter_lints: ^1.0.0

  flutter_cache_manager_firebase: ^2.0.1

  json_serializable: ^6.2.0

  mockito: ^5.1.0

flutter:

  uses-material-design: true

