// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_project/test/app/features/data/repositories/product_repository_data_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_project/app/features/data/data_sources/product_data_source.dart'
    as _i2;
import 'package:flutter_project/app/features/domain/entities/product_entity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [IProductDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductDataSource extends _i1.Mock
    implements _i2.IProductDataSource {
  MockIProductDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductEntity>> fetchProducts() =>
      (super.noSuchMethod(Invocation.method(#fetchProducts, []),
              returnValue:
                  Future<List<_i4.ProductEntity>>.value(<_i4.ProductEntity>[]))
          as _i3.Future<List<_i4.ProductEntity>>);
  @override
  _i3.Future<dynamic> updateProduct(_i4.ProductEntity? product) =>
      (super.noSuchMethod(Invocation.method(#updateProduct, [product]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> deleteProduct(int? id) =>
      (super.noSuchMethod(Invocation.method(#deleteProduct, [id]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
